version: '3'
services:
  hubot:
    build: .
    env_file: .env
    restart: unless-stopped
    ports:
      - "80:8080"
  redis:
    image: "redis:alpine"
    command: ["redis-server", "--appendonly", "yes"]
    restart: unless-stopped
    volumes:
      - brain:/data
volumes:
  brain:
